language: cpp
sudo: false

matrix:
  include:
    - os: linux
      dist: precise
      compiler: clang
    - os: linux
      dist: precise
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: clang
    - os: linux
      dist: trusty
      compiler: gcc
    - os: osx
addons:
  apt:
    packages:
    - ninja-build

before_install:
  - "if [ $TRAVIS_OS_NAME = 'osx' ]; then brew install ninja; fi"
script:
  - "$CXX $(find src -name \"*.cpp\") -Isrc -o phoenix_bootstrapped -std=c++0x -O2"
  - ./phoenix_bootstrapped .
  - ninja
  - ./utiltest
  - ./scripttest
  - mkdir build-self && cd build-self
  - ../phoenix ..
  - ninja

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7e83f2fe7e79082d1ad8
    on_success: change
    on_failure: always
