sudo: false
language: cpp
os:
  - linux
  - osx
addons:
  apt:
    packages:
    - ninja-build
compiler:
  - gcc
  - clang
matrix:
  fast_finish: true
  exclude:
    - os: osx
      compiler: gcc
      # "gcc" on OS X is just Clang in fake-GCC mode

before_install:
  - "if [ $TRAVIS_OS_NAME = 'osx' ]; then brew install ninja; fi"
script:
  - "g++ $(find src -name \"*.cpp\") -Isrc -o phoenix_bootstrapped -std=c++0x -O2"
  - ./phoenix_bootstrapped .
  - ninja
  - build-utiltest/utiltest
  - build-scripttest/scripttest
  - mkdir build-self && cd build-self
  - ../build-phoenix/phoenix ..
  - ninja

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7e83f2fe7e79082d1ad8
    on_success: change
    on_failure: always
