sudo: false
language: cpp
os:
  - linux
  - osx
addons:
  apt:
    packages:
    - ninja-build
compiler:
  - gcc
  - clang
matrix:
  fast_finish: true
  exclude:
    - os: osx
      compiler: gcc
      # "gcc" on OS X is just Clang in fake-GCC mode

before_install:
  - "if [ $TRAVIS_OS_NAME = 'osx' ]; then brew install ninja; fi"
script:
  - ./tools/bootstrap.sh
  - ./phoenix_bootstrapped .
  - ninja

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7e83f2fe7e79082d1ad8
    on_success: change
    on_failure: always
